//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_20.BD_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accont_insurance
    {
        public string id_accountant { get; set; }
        public int id_insurance_company { get; set; }
        public System.DateTime date_of_creation { get; set; }
        public string bill { get; set; }
    
        public virtual Accountants Accountants { get; set; }
        public virtual Insurance_company Insurance_company { get; set; }
    }
}
