//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_20.BD_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public string id_admin { get; set; }
        public string photo { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
