//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_20.BD_model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Med_lab_20Entities : DbContext
    {
        private static Med_lab_20Entities _Context;
        public Med_lab_20Entities()
            : base("name=Med_lab_20Entities")
        {
        }

        public static Med_lab_20Entities GetContext()
        {
            if (_Context == null)
                _Context = new Med_lab_20Entities();
            return _Context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accont_insurance> Accont_insurance { get; set; }
        public virtual DbSet<Accountants> Accountants { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Analyzer> Analyzer { get; set; }
        public virtual DbSet<History_of_analyzers> History_of_analyzers { get; set; }
        public virtual DbSet<Insurance_company> Insurance_company { get; set; }
        public virtual DbSet<Laboratorian> Laboratorian { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Package_of_services> Package_of_services { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Services_rendered> Services_rendered { get; set; }
        public virtual DbSet<Session_history> Session_history { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
