//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_20.BD_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_of_analyzers
    {
        public int id { get; set; }
        public int id_analyzer { get; set; }
        public System.DateTime date_of_receipt { get; set; }
        public string date_of_execution { get; set; }
    
        public virtual Analyzer Analyzer { get; set; }
    }
}
