//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_20.BD_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_of_services
    {
        public int id_order { get; set; }
        public int id_services { get; set; }
        public string services_status { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Services Services { get; set; }
    }
}
