//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_20.BD_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id_patient { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string full_name { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public int passport { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public int insurance_policy { get; set; }
        public string type_police { get; set; }
        public int id_insurance_company { get; set; }
    
        public virtual Insurance_company Insurance_company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
