//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_20.BD_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_rendered
    {
        public int id_services { get; set; }
        public string id_laboratorian { get; set; }
        public int id_analyzer { get; set; }
        public Nullable<System.DateTime> time_of_rendered { get; set; }
    
        public virtual Analyzer Analyzer { get; set; }
        public virtual Laboratorian Laboratorian { get; set; }
        public virtual Services Services { get; set; }
    }
}
