//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Med_20.BD_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session_history
    {
        public int id_session { get; set; }
        public string id_user { get; set; }
        public Nullable<System.DateTime> Date_of_enter { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public bool IsSuccess { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
